version: "3.8"

services:
  app:
    image: "app:latest"
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cip
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=221293
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=221293
      - POSTGRES_DB=cip
